version: "3"
services:

  redis-node-0:
    image: redis:latest
    container_name: redis-node-0
    volumes: # 작성한 설정 파일을 볼륨을 통해 컨테이너에 공유
      - ./redis0.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7000:7000"
      - "17000:17000"

  redis-node-1:
    image: redis:latest
    container_name: redis-node-1
    volumes:
      - ./redis1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7001:7001"
      - "17001:17001"

  redis-node-2:
    image: redis:latest
    container_name: redis-node-2
    volumes:
      - ./redis2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7002:7002"
      - "17002:17002"

  redis-node-3:
    image: redis:latest
    container_name: redis-node-3
    volumes:
      - ./redis3.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7003:7003"
      - "17003:17003"

  redis-node-4:
    image: redis:latest
    container_name: redis-node-4
    volumes:
      - ./redis4.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7004:7004"
      - "17004:17004"

  redis-node-5:
    image: redis:latest
    container_name: redis-node-5
    volumes:
      - ./redis5.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7005:7005"
      - "17005:17005"


  redis-cluster-entry:
    image: redis:latest
    container_name: redis-cluster-entry
    command:
      - "sh"
      - "-c"
      - |
        redis-cli --cluster create 192.168.158.160:7000 192.168.158.160:7001 192.168.158.160:7002 --cluster-yes --cluster-replicas 0
        redis-cli --cluster add-node 192.168.158.160:7003 192.168.158.160:7000 --cluster-slave
        redis-cli --cluster add-node 192.168.158.160:7004 192.168.158.160:7001 --cluster-slave
        redis-cli --cluster add-node 192.168.158.160:7005 192.168.158.160:7002 --cluster-slave
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5